language: node_js
node_js:
  - v8
dist: trusty # needs Ubuntu Trusty
addons:
  - chrome # or google-chrome-stable
before_install:
  - sudo apt-get install g++ build-essential # Build essential to compile the integration-test platform
  - sudo apt-get install oracle-java8-set-default # Java instalation for webdriverio
  - CHROME_BIN=google-chrome # Set chrome bin path for karma tests runner
  - export DISPLAY=:99.0 # Display size
  - sh -e /etc/init.d/xvfb start # Start X-window to run chrome
before_script:
  - npm install -g gulp-cli
script:
  - gulp
  - gulp test
cache:
  directories:
    - node_modules
notifications:
  email: false
